#!/usr/bin/env python3
# gen_tb.py — generate a sim_tb.v (1 master + N slaves on a shared, idle-high
# serial bus) from a JSON config. Emits the same module name / port list as the
# hand-written sim_tb, so the existing harness + makefile build it unchanged:
#
#   python3 gen_tb.py sim_config.json -o src/sim_tb_gen.v
#   make -f sim.mk simtb-run SIM_TB_V=src/sim_tb_gen.v
#
# Register init is not emitted yet (roadmap item: verilator-public poke from
# the harness). A "registers" key is accepted but ignored for now.

import argparse
import json
import sys


def die(msg):
    sys.stderr.write("gen_tb: error: %s\n" % msg)
    sys.exit(1)


def parse_addr(a):
    # accept 17, "17", or "0x11"
    if isinstance(a, int):
        return a
    if isinstance(a, str):
        return int(a, 0)
    die("slave addr must be int or string, got %r" % (a,))


def load_config(path):
    try:
        with open(path) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        die("config not found: %s" % path)
    except json.JSONDecodeError as e:
        die("invalid JSON in %s: %s" % (path, e))

    slaves = cfg.get("slaves")
    if not isinstance(slaves, list) or not slaves:
        die('config needs a non-empty "slaves" array')

    addrs = []
    for i, s in enumerate(slaves):
        if not isinstance(s, dict) or "addr" not in s:
            die('slaves[%d] needs an "addr" field' % i)
        addr = parse_addr(s["addr"])
        if not (1 <= addr <= 247):
            die("slaves[%d] addr %d out of Modbus range 1..247" % (i, addr))
        addrs.append(addr)

    dupes = sorted({a for a in addrs if addrs.count(a) > 1})
    if dupes:
        die(
            "duplicate slave addresses: %s (would cause bus contention)"
            % ", ".join("0x%02X" % a for a in dupes)
        )

    err = cfg.get("errors", {})
    if not isinstance(err, dict):
        die('"errors" must be an object')
    direction = err.get("direction", "request")
    if direction not in ("request", "response", "both"):
        die("errors.direction must be request | response | both")
    errors = {
        "enable": bool(err.get("enable", False)),
        "seed": parse_addr(err.get("seed", "0xACE12345")),
        "rate_ppm": int(err.get("rate_ppm", 1000)),
        "direction": direction,
    }

    return {
        "clk_freq": int(cfg.get("clk_freq", 1_000_000)),
        "baud_rate": int(cfg.get("baud_rate", 100_000)),
        "max_retries": int(cfg.get("max_retries", 2)),
        "module": cfg.get("module", "sim_tb"),
        "addrs": addrs,
        "errors": errors,
    }


def hx(addr):
    return "8'h%02X" % addr


def render(cfg):
    addrs = cfg["addrs"]
    n = len(addrs)
    L = []

    L.append("`timescale 1ns/1ps")
    L.append("")
    L.append("// AUTO-GENERATED by gen_tb.py — do not edit by hand.")
    L.append("// 1 master + %d slave(s) on a shared idle-high serial bus." % n)
    L.append("// Bus: master TX broadcasts to all slave RX; slave TX lines are")
    L.append("// wired-AND back to master RX (only the addressed slave drives low).")
    L.append("")
    L.append("module %s #(" % cfg["module"])
    L.append("  parameter CLK_FREQ       = %d," % cfg["clk_freq"])
    L.append("  parameter BAUD_RATE      = %d," % cfg["baud_rate"])
    L.append("  parameter MAX_RETRIES    = %d," % cfg["max_retries"])
    L.append("  parameter TIMEOUT_CYCLES = (CLK_FREQ / BAUD_RATE) * 200")
    L.append(")(")
    L.append("  input  wire        clk,")
    L.append("  input  wire        rstb,")
    L.append("")
    L.append("  // master host interface — driver writes")
    L.append("  input  wire [7:0]  host_byte_in,")
    L.append("  input  wire        host_byte_valid,")
    L.append("  input  wire        host_frame_done,")
    L.append("")
    L.append("  // master host interface — driver reads")
    L.append("  output wire        host_byte_ready,")
    L.append("  output wire [7:0]  host_byte_out,")
    L.append("  output wire        host_byte_out_valid,")
    L.append("  output wire        host_frame_out_done,")
    L.append("  output wire        req_ready,")
    L.append("  output wire        req_timeout,")
    L.append("  output wire        req_failed")
    L.append(");")
    L.append("")

    # bus wires + optional fault injectors
    tx_names = ["s%d_tx" % i for i in range(n)]
    err = cfg["errors"]
    corrupt_req = err["enable"] and err["direction"] in ("request", "both")
    corrupt_resp = err["enable"] and err["direction"] in ("response", "both")

    # net the master drives / listens to, and the net the slaves listen to
    master_tx_net = "master_tx_clean" if corrupt_req else "master_to_slaves"
    slave_rx_net = "master_to_slaves"
    master_rx_net = "slaves_to_master"

    L.append("  wire %s;" % ", ".join(tx_names))
    if corrupt_req:
        L.append("  wire master_tx_clean;")
        L.append("  wire master_to_slaves;")
    else:
        L.append("  wire master_to_slaves;")

    if corrupt_resp:
        L.append("  wire slaves_to_master_clean = %s;" % " & ".join(tx_names))
        L.append("  wire slaves_to_master;")
    else:
        L.append("  wire slaves_to_master = %s;" % " & ".join(tx_names))
    L.append("")

    def emit_injector(name, seed, line_in, line_out):
        L.append("  line_fault #(")
        L.append("    .CLK_FREQ (CLK_FREQ),")
        L.append("    .BAUD_RATE(BAUD_RATE),")
        L.append("    .SEED     (32'h%08X)," % (seed & 0xFFFFFFFF))
        L.append("    .RATE_PPM (%d)" % err["rate_ppm"])
        L.append("  ) %s (" % name)
        L.append("    .clk(clk), .rstb(rstb), .enable(1'b1),")
        L.append("    .line_in(%s), .line_out(%s)" % (line_in, line_out))
        L.append("  );")
        L.append("")

    if corrupt_req:
        emit_injector("fault_req", err["seed"], "master_tx_clean", "master_to_slaves")
    if corrupt_resp:
        emit_injector(
            "fault_resp",
            err["seed"] ^ 0xFFFFFFFF,
            "slaves_to_master_clean",
            "slaves_to_master",
        )

    # master
    L.append("  modbus_top #(")
    L.append("    .DEFAULT_SLAVE_ADDR(%s)," % hx(addrs[0]))
    L.append("    .CLK_FREQ          (CLK_FREQ),")
    L.append("    .BAUD_RATE         (BAUD_RATE),")
    L.append("    .MAX_RETRIES       (MAX_RETRIES),")
    L.append("    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)")
    L.append("  ) dut_master (")
    L.append("    .clk                (clk),")
    L.append("    .rstb               (rstb),")
    L.append("    .mode               (1'b1),")
    L.append("    .ser_rx             (%s)," % master_rx_net)
    L.append("    .ser_tx             (%s)," % master_tx_net)
    L.append("    .slave_addr         (%s)," % hx(addrs[0]))
    L.append("    .host_byte_in       (host_byte_in),")
    L.append("    .host_byte_valid    (host_byte_valid),")
    L.append("    .host_byte_ready    (host_byte_ready),")
    L.append("    .host_frame_done    (host_frame_done),")
    L.append("    .host_byte_out      (host_byte_out),")
    L.append("    .host_byte_out_valid(host_byte_out_valid),")
    L.append("    .host_frame_out_done(host_frame_out_done),")
    L.append("    .req_ready          (req_ready),")
    L.append("    .req_timeout        (req_timeout),")
    L.append("    .req_failed         (req_failed)")
    L.append("  );")
    L.append("")

    # slaves
    for i, addr in enumerate(addrs):
        L.append("  modbus_top #(")
        L.append("    .DEFAULT_SLAVE_ADDR(%s)," % hx(addr))
        L.append("    .CLK_FREQ          (CLK_FREQ),")
        L.append("    .BAUD_RATE         (BAUD_RATE),")
        L.append("    .MAX_RETRIES       (MAX_RETRIES),")
        L.append("    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)")
        L.append("  ) dut_slave%d (" % i)
        L.append("    .clk(clk), .rstb(rstb), .mode(1'b0),")
        L.append("    .ser_rx(master_to_slaves), .ser_tx(s%d_tx)," % i)
        L.append("    .slave_addr(%s)," % hx(addr))
        L.append(
            "    .host_byte_in(8'h00), .host_byte_valid(1'b0), .host_byte_ready(),"
        )
        L.append(
            "    .host_frame_done(1'b0), .host_byte_out(), .host_byte_out_valid(),"
        )
        L.append(
            "    .host_frame_out_done(), .req_ready(), .req_timeout(), .req_failed()"
        )
        L.append("  );")
        L.append("")

    L.append("endmodule")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description="Generate sim_tb.v from JSON config.")
    ap.add_argument("config", help="path to JSON config")
    ap.add_argument(
        "-o",
        "--output",
        default="src/sim_tb_gen.v",
        help="output .v path (default: src/sim_tb_gen.v; - for stdout)",
    )
    args = ap.parse_args()

    cfg = load_config(args.config)
    text = render(cfg)

    if args.output == "-":
        sys.stdout.write(text)
    else:
        with open(args.output, "w") as f:
            f.write(text)
        sys.stderr.write(
            "gen_tb: wrote %s (%d slave(s): %s)\n"
            % (
                args.output,
                len(cfg["addrs"]),
                ", ".join("0x%02X" % a for a in cfg["addrs"]),
            )
        )


if __name__ == "__main__":
    main()
