`timescale 1ns/1ps

// AUTO-GENERATED by gen_tb.py — do not edit by hand.
// 1 master + 4 slave(s) on a shared idle-high serial bus.
// Bus: master TX broadcasts to all slave RX; slave TX lines are
// wired-AND back to master RX (only the addressed slave drives low).

module sim_tb #(
  parameter CLK_FREQ       = 1000000,
  parameter BAUD_RATE      = 100000,
  parameter MAX_RETRIES    = 2,
  parameter TIMEOUT_CYCLES = (CLK_FREQ / BAUD_RATE) * 200
)(
  input  wire        clk,
  input  wire        rstb,

  // master host interface — driver writes
  input  wire [7:0]  host_byte_in,
  input  wire        host_byte_valid,
  input  wire        host_frame_done,

  // master host interface — driver reads
  output wire        host_byte_ready,
  output wire [7:0]  host_byte_out,
  output wire        host_byte_out_valid,
  output wire        host_frame_out_done,
  output wire        req_ready,
  output wire        req_timeout,
  output wire        req_failed
);

  wire master_to_slaves;
  wire s0_tx, s1_tx, s2_tx, s3_tx;
  wire slaves_to_master = s0_tx & s1_tx & s2_tx & s3_tx;

  modbus_top #(
    .DEFAULT_SLAVE_ADDR(8'h11),
    .CLK_FREQ          (CLK_FREQ),
    .BAUD_RATE         (BAUD_RATE),
    .MAX_RETRIES       (MAX_RETRIES),
    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)
  ) dut_master (
    .clk                (clk),
    .rstb               (rstb),
    .mode               (1'b1),
    .ser_rx             (slaves_to_master),
    .ser_tx             (master_to_slaves),
    .slave_addr         (8'h11),
    .host_byte_in       (host_byte_in),
    .host_byte_valid    (host_byte_valid),
    .host_byte_ready    (host_byte_ready),
    .host_frame_done    (host_frame_done),
    .host_byte_out      (host_byte_out),
    .host_byte_out_valid(host_byte_out_valid),
    .host_frame_out_done(host_frame_out_done),
    .req_ready          (req_ready),
    .req_timeout        (req_timeout),
    .req_failed         (req_failed)
  );

  modbus_top #(
    .DEFAULT_SLAVE_ADDR(8'h11),
    .CLK_FREQ          (CLK_FREQ),
    .BAUD_RATE         (BAUD_RATE),
    .MAX_RETRIES       (MAX_RETRIES),
    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)
  ) dut_slave0 (
    .clk(clk), .rstb(rstb), .mode(1'b0),
    .ser_rx(master_to_slaves), .ser_tx(s0_tx),
    .slave_addr(8'h11),
    .host_byte_in(8'h00), .host_byte_valid(1'b0), .host_byte_ready(),
    .host_frame_done(1'b0), .host_byte_out(), .host_byte_out_valid(),
    .host_frame_out_done(), .req_ready(), .req_timeout(), .req_failed()
  );

  modbus_top #(
    .DEFAULT_SLAVE_ADDR(8'h12),
    .CLK_FREQ          (CLK_FREQ),
    .BAUD_RATE         (BAUD_RATE),
    .MAX_RETRIES       (MAX_RETRIES),
    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)
  ) dut_slave1 (
    .clk(clk), .rstb(rstb), .mode(1'b0),
    .ser_rx(master_to_slaves), .ser_tx(s1_tx),
    .slave_addr(8'h12),
    .host_byte_in(8'h00), .host_byte_valid(1'b0), .host_byte_ready(),
    .host_frame_done(1'b0), .host_byte_out(), .host_byte_out_valid(),
    .host_frame_out_done(), .req_ready(), .req_timeout(), .req_failed()
  );

  modbus_top #(
    .DEFAULT_SLAVE_ADDR(8'h13),
    .CLK_FREQ          (CLK_FREQ),
    .BAUD_RATE         (BAUD_RATE),
    .MAX_RETRIES       (MAX_RETRIES),
    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)
  ) dut_slave2 (
    .clk(clk), .rstb(rstb), .mode(1'b0),
    .ser_rx(master_to_slaves), .ser_tx(s2_tx),
    .slave_addr(8'h13),
    .host_byte_in(8'h00), .host_byte_valid(1'b0), .host_byte_ready(),
    .host_frame_done(1'b0), .host_byte_out(), .host_byte_out_valid(),
    .host_frame_out_done(), .req_ready(), .req_timeout(), .req_failed()
  );

  modbus_top #(
    .DEFAULT_SLAVE_ADDR(8'h01),
    .CLK_FREQ          (CLK_FREQ),
    .BAUD_RATE         (BAUD_RATE),
    .MAX_RETRIES       (MAX_RETRIES),
    .TIMEOUT_CYCLES    (TIMEOUT_CYCLES)
  ) dut_slave3 (
    .clk(clk), .rstb(rstb), .mode(1'b0),
    .ser_rx(master_to_slaves), .ser_tx(s3_tx),
    .slave_addr(8'h01),
    .host_byte_in(8'h00), .host_byte_valid(1'b0), .host_byte_ready(),
    .host_frame_done(1'b0), .host_byte_out(), .host_byte_out_valid(),
    .host_frame_out_done(), .req_ready(), .req_timeout(), .req_failed()
  );

endmodule
